### ISSUE TITLE
Support remote references for modules & partials

### ISSUE THREAD

**Issue by robzienert** [spinnaker/dcd-spec#17]
It would be valuable to be able to publish & reference remote modules & partials within templates and configurations. This could either be explicitly declared as part of #4, then given aliases for reference, or just directly referenced at call-site.

```yaml
# Template snippet
id: myExampleTemplate
metadata:
  name: myExampleTemplate
  description: Modules example template
  owner: example@example.com
  scopes: [global]
variables:
- name: regions
  description: A list of AWS regions to deploy into
  type: list
stages:
- id: deploy
  type: deploy
  config:
    clusters: |
      {% for region in regions %}
      - {% module spinnaker://deployClusterAws region=region %}
      {% endfor %}

# Stored totally separately in a different object.
modules:
- id: deployClusterAws
  usage: Defines a deploy stage cluster using the AWS cloud provider
  variables:
  - name: region
    description: The AWS region to deploy into
  when: 
  - "{{ region != 'ap-northeast-1' }}"
  definition:
    provider: aws
    account: myAccount
    region: "{{ region }}"
```
