### ISSUE TITLE
Modules - When conditions are not working

### ISSUE THREAD

**Issue by loheswaran** [spinnaker/dcd-spec#25]
**Stage Definition**
```
variables:
- name: secrets
  type: list
  defaultValue:
  - name: NA
    envVars:
    - NA
- id: deployToDev
  type: deploy
  name: Deploy to Dev
  config:
    clusters:
    - account: dcomdev03
      application: "test"
      cloudProvider: kubernetes
      containers:
      - envVars: |
          {% for secret in secrets %}
          {% for envVar in secret.envVars %}
          - {% module secretsEnvSourceModule envName=envVar secretName=secret.name %}
          {% endfor %}
          {% endfor %}
```

**Module Definition**
```
modules:
- id: secretsEnvSourceModule
  usage: Defines the env source for exposing secrets as env variables
  variables:
  - name: envName
    description: env variable name
  - name: secretName
    description: Secret Name
  when: 
  - "{{ secretName != 'NA' }}"
  definition:
    envSource:
      secretSource:
        secretName: "{{ secretName }}"
        key: "{{ envName }}"
    name: "{{ envName }}"
```

**Pipeline**
<img width="897" alt="screen shot 2018-06-01 at 6 34 10 pm" src="https://user-images.githubusercontent.com/8875426/40842153-86521b92-65ca-11e8-8f2a-613761abc216.png">
